### ISSUE TITLE
sudo make fails.

### ISSUE THREAD

**Issue by HubKing** [jj11hh/samsung-laptop#3]
```
Building module:
cleaning build area...
make -j4 KERNELRELEASE=5.10.89-1-MANJARO all KVERSION=5.10.89-1-MANJARO...(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.10.89-1-MANJARO (x86_64)
Consult /var/lib/dkms/samsung-laptop-dang/1.0/build/make.log for more information.
make: *** [Makefile:9: install] Error 10
```

make.log

```
DKMS make.log for samsung-laptop-dang-1.0 for kernel 5.10.89-1-MANJARO (x86_64)
Wed 12 Jan 20:22:58 JST 2022
make[1]: Entering directory '/var/lib/dkms/samsung-laptop-dang/1.0/build'
make -C /lib/modules/5.10.89-1-MANJARO/build  M=/var/lib/dkms/samsung-laptop-dang/1.0/build modules
make[2]: Entering directory '/usr/lib/modules/5.10.89-1-MANJARO/build'
  CC [M]  /var/lib/dkms/samsung-laptop-dang/1.0/build/samsung-laptop-dang.o
/var/lib/dkms/samsung-laptop-dang/1.0/build/samsung-laptop-dang.c: In function ‘samsung_debugfs_init’:
/var/lib/dkms/samsung-laptop-dang/1.0/build/samsung-laptop-dang.c:1323:14: error: void value not ignored as it ought to be
 1323 |         dent = debugfs_create_u16("command", S_IRUGO | S_IWUSR,
      |              ^
/var/lib/dkms/samsung-laptop-dang/1.0/build/samsung-laptop-dang.c:1328:14: error: void value not ignored as it ought to be
 1328 |         dent = debugfs_create_u32("d0", S_IRUGO | S_IWUSR, samsung->debug.root,
      |              ^
/var/lib/dkms/samsung-laptop-dang/1.0/build/samsung-laptop-dang.c:1333:14: error: void value not ignored as it ought to be
 1333 |         dent = debugfs_create_u32("d1", S_IRUGO | S_IWUSR, samsung->debug.root,
      |              ^
/var/lib/dkms/samsung-laptop-dang/1.0/build/samsung-laptop-dang.c:1338:14: error: void value not ignored as it ought to be
 1338 |         dent = debugfs_create_u16("d2", S_IRUGO | S_IWUSR, samsung->debug.root,
      |              ^
/var/lib/dkms/samsung-laptop-dang/1.0/build/samsung-laptop-dang.c:1343:14: error: void value not ignored as it ought to be
 1343 |         dent = debugfs_create_u8("d3", S_IRUGO | S_IWUSR, samsung->debug.root,
      |              ^
/var/lib/dkms/samsung-laptop-dang/1.0/build/samsung-laptop-dang.c: In function ‘samsung_sabi_init’:
/var/lib/dkms/samsung-laptop-dang/1.0/build/samsung-laptop-dang.c:1461:34: error: implicit declaration of function ‘ioremap_nocache’; did you mean ‘ioremap_cache’? [-Werror=implicit-function-declaration]
 1461 |         samsung->f0000_segment = ioremap_nocache(0xf0000, 0xffff);
      |                                  ^~~~~~~~~~~~~~~
      |                                  ioremap_cache
/var/lib/dkms/samsung-laptop-dang/1.0/build/samsung-laptop-dang.c:1461:32: warning: assignment to ‘void *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
 1461 |         samsung->f0000_segment = ioremap_nocache(0xf0000, 0xffff);
      |                                ^
/var/lib/dkms/samsung-laptop-dang/1.0/build/samsung-laptop-dang.c:1501:29: warning: assignment to ‘void *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
 1501 |         samsung->sabi_iface = ioremap_nocache(ifaceP, 16);
      |                             ^
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:280: /var/lib/dkms/samsung-laptop-dang/1.0/build/samsung-laptop-dang.o] Error 1
make[2]: *** [Makefile:1822: /var/lib/dkms/samsung-laptop-dang/1.0/build] Error 2
make[2]: Leaving directory '/usr/lib/modules/5.10.89-1-MANJARO/build'
make[1]: *** [Makefile:15: default] Error 2
make[1]: Leaving directory '/var/lib/dkms/samsung-laptop-dang/1.0/build'
```

cc --version: cc (GCC) 11.1.0
